import type { NextPage } from "next";
import Head from "next/head";
import CarouselComponent from "../src/components/CarouselComponent";
import { CaseContainer, CaseCard } from "../src/components/Cases";
import Hero from "../src/components/Hero";
import Test from "../src/test";
const Home: NextPage = () => {
  return (
    <div className="w-full ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-4xl mx-auto">
        <Hero />
        <section className="pt-8 pb-14 px-4 relative">
          <h2 className="text-center text-xl font-semibold mb-6">
            Data Kasus Covid-19
          </h2>
          <h3 className="text-center text-md font-semibold mb-6">Hari ini</h3>
          <CaseContainer>
            <CaseCard status="positif" jumlah={100} />
            <CaseCard status="dirawat" jumlah={88} />
            <CaseCard status="sembuh" jumlah={5} />
            <CaseCard status="meninggal" jumlah={2} />
          </CaseContainer>
          <h3 className="my-6 text-center text-md font-semibold">Total</h3>
          <CaseContainer>
            <CaseCard status="positif" jumlah={100} />
            <CaseCard status="dirawat" jumlah={88} />
            <CaseCard status="sembuh" jumlah={5} />
            <CaseCard status="meninggal" jumlah={2} />
          </CaseContainer>
          <span className="text-xs text-blue-700 absolute bottom-2 right-2">
            Terakhir kali data di-update: 26 Mei 2022
          </span>
        </section>
        <Test />
        <CarouselComponent />
      </main>
    </div>
  );
};

export default Home;
